### ISSUE TITLE
DNS hierarchical deployment

### ISSUE THREAD

**Issue by cleverchou** [samboy/MaraDNS#94] opened 2021-02-22 08:51 UTC
How to configure support for  hierarchical deployment
The root . Deployed on server 1, and the .com is deployed on server 2

**Comment by samboy** [comment] 2021-02-24 20:46
This is a support question, not a bug report. Closing; please use the “discussions” tab for support requests.

**Closed by samboy** 2021-02-24 20:46 UTC

**Comment by samboy** [comment] 2021-02-24 20:48
Support is here: https://github.com/samboy/MaraDNS/discussions/87

I have had entitled users get upset about there being support boundaries in the past, so the conversation is locked to avoid that happening here (I’m not saying you’ll do it, so please do not take this personally).
