### ISSUE TITLE
Cannot resolve certain domain

### ISSUE THREAD

**Issue by dnsconfused** [samboy/MaraDNS#54] opened 2019-02-19 15:23 UTC
It would seem this certain domain does not resolve through Deadwood...
baas-fes-eu3-acs1.acronis.com

...this name is a CNAME (???) for abgw-eu3-acs1.acronis.com which does resolve through Deadwood, and returns allot of IPs.

As an aside, not sure why Acronis decided this was the best way to do this.

**Comment by samboy** [comment] 2019-02-23 18:06
The problem is this: The nameserver there is sending a reply which is just over 512 bytes in size, but the truncated reply does not give Deadwood any information which can be used:

```
10:00 ~ $ askmara Abaas-fes-eu3-acs1.acronis.com. 205.251.193.189
# Querying the server with the IP 205.251.193.189
# Remote server said: TRUNCATED
# Question: Abaas-fes-eu3-acs1.acronis.com.
# NS replies:
# AR replies:
```

Normally, when a DNS server truncates a reply, it sends the first 512 bytes down anyway; Deadwood is designed to, when it sees a truncated packet with some information, process that information.  Unfortunately, this DNS server does things the wrong way, giving us no useful information when giving us a truncated reply (I believe the standards ask for this behavior, but it’s the wrong way to do things, since it breaks DjbDNS and any other DNS server with EDNS0).

For me to fix this requires me to implement EDNS0 in Deadwood; doing that will be, to put it mildly, non-trivial, since EDNS0 is an ugly hack tacked on to DNS.  Since I’m not going to get paid for this work, I am going to close this as “WONTFIX”.  :(

The workaround is to use `upstream_servers`, not `root_servers`, like this (this uses Google’s DNS servers, which correctly send a non-truncated reply to downstream resolvers):

```python
upstream_servers = {}
upstream_servers["."] = "8.8.8.8, 8.8.4.4"
```

**Closed by samboy** 2019-02-23 18:06 UTC

**Comment by samboy** [comment] 2019-02-23 19:13
Related issue: https://github.com/samboy/MaraDNS/issues/31

**Comment by samboy** [comment] 2019-03-30 21:01
Locking conversation to stop spam.

**Comment by samboy** [comment] 2020-09-10 23:17
See also: https://github.com/samboy/MaraDNS/issues/31 https://github.com/samboy/MaraDNS/issues/56
