### ISSUE TITLE
Support CAA Record

### ISSUE THREAD

**Issue by PavelSpiridonov** [samboy/MaraDNS#38] opened 2017-09-15 06:05 UTC
Do you plan to implement support for CAA records? (https://sslmate.com/caa/about)

**Comment by samboy** [comment] 2017-09-16 05:25
No.

This is a dupe of https://github.com/samboy/MaraDNS/issues/35

Read that ticket to see how to get CAA records to work in MaraDNS.

Closing.

**Closed by samboy** 2017-09-16 05:25 UTC
