### ISSUE TITLE
[request] Any way to have microdns for Windows?

### ISSUE THREAD

**Issue by oneohthree** [samboy/MaraDNS#68] opened 2020-02-21 23:15 UTC
Is there any way to compile microdns for Windows (or the binary file)? If so, could you provide the procedure?

**Comment by samboy** [comment] 2020-03-02 23:48
There are several ways to have `microdns` (and pretty much any other program written for Linux/UNIX) run in Windows.  To name just three:

* [Cygwin](https://cygwin.com)
* [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* [VMware player](https://www.vmware.com/products/workstation-player.html) along with a Linux boot `.iso` image

I have verified that microdns compiles and runs in Cygwin. Other environments will also work as well.

The real solution is for me to make an official [Docker](https://www.docker.com/) container for MaraDNS, Deadwood, and microdns, so the “I want to run this in my OS” requests can be answered with: “Well, if your OS has Docker, just run the appropriate container”. Windows 10 has Docker. Mac OS has Docker. Linux has Docker. Write once, run anywhere.

I consider this a dupe of https://github.com/samboy/MaraDNS/issues/67. Closing.

**Closed by samboy** 2020-03-02 23:48 UTC

**Comment by samboy** [comment] 2020-03-09 21:17
Locking conversation to protect it from spammers.

**Comment by samboy** [comment] 2020-06-02 14:55
I am working on addressing this feature request  in https://github.com/samboy/MaraDNS/issues/76

The plan is to have people who need `maradns` as an authoritative server or `microdns` to use Cygwin to compile and run the programs.

**Comment by samboy** [comment] 2020-06-19 10:00
Note that I have not tested this, but to compile and run microdns:

* Go to https://cygwin.com/ and download and install Cygwin
* When installing Cygwin, be sure to install both "gcc" and "make"
* Get the source code for MaraDNS
* From the MaraDNS-3.5.{version} directory, where {version} is the number
  0005 or higher, type in the following commands from the Cygwin command
  prompt:

	`cd tools/misc ; gcc -O2 -o microdns microdns.c`
	`cygrunsrv.exe --install microdns --path /usr/local/bin/microdns.exe --args 10.1.2.3`
	`cygrunsrv.exe -S microdns`

* microdns now runs as a service.

**Comment by samboy** [comment] 2020-07-23 09:34
For Windows users who are not comfortable with cygwin, I have made a Windows 32 service with a “microDNS on seroids” program.  This works like microdns: It can return the same IP for any and all DNS query sent to it (and, unlike microDNS, it handles EDNS packets).

However, unlike microdns, it is fully customizable.  It uses a copy of my fork of the entire Lua 5.1 engine.

(Why the old 5.1 version? It’s smaller than 5.3/5.4, and Lua 5.1 is the “Lingua Franca” version of Lua: LuaJIT is Lua 5.1 compatible, Gopher Lua is Lua 5.1 compatible, luau (Roblox Lua) is Lua 5.1 compatible, etc.)

What this code does is run a Lua function every time we get a DNS query. That function knows the name and query type for the question. The Lua code can either return a user-selectable IP, or tell the DNS server to ignore the DNS query.  This allows some amount of customization (like allowing all `.com` answers return a different IP), while keeping the code fairly simple.

The code can be looked at here:

https://github.com/samboy/lunacy/tree/master/mmLunacyDNS

I plan on making this part of MaraDNS.

**Comment by samboy** [comment] 2020-07-25 08:06
mmLunacyDNS is now included as a Windows binary in MaraDNS 3.5.0008. It’s not exactly the same as microDNS (it handles EDNS packets correctly; it can run as a native Windows service; and it has Lua support for maximum flexibility with the A responses the server sends). Not exactly microDNS, but close enough that I’m now marking this ticket “Done”.

**Comment by samboy** [comment] 2020-08-24 03:34
mmLunacyDNS is being phased out, but coLunacyDNS (which is now stable) can also do this, e.g.

```lua
bindIp = "127.0.0.1" -- We bind the server to the IP 127.0.0.1
function processQuery(Q) -- Called for every DNS query received
  return {co1Type = "A", co1Data = "10.1.1.1"}
end
````

**Comment by samboy** [comment] 2020-09-10 22:07
mmLunacyDNS has been replaced by the now-stable `coLunacyDNS`.  Use that instead.
