### ISSUE TITLE
Zone cut NS RRs returned as authoritative records

### ISSUE THREAD

**Issue by SivaKesava1** [samboy/MaraDNS#85] opened 2020-11-01 17:19 UTC
Hi,

Similar to #84, the issue exists with child NS records also. Consider the same zone file,

|  	|  	|  	|  	|
|-	|-	|-	|-	|
| example.com. 	| +60480 	| SOA 	| ns1.outside.com. root.example.com. 3 604800 86400 2419200 604800 ~ 	|
| example.com. 	| +60480 	| NS 	| ns1.outside.com. ~ 	|
| b.g.example.com. 	| +60480 	| NS 	| n.b.g.example.com. ~ 	|
| n.b.g.example.com. 	| +60480 	| A 	| 1.1.1.1 ~ 	|

For the query _<b.g.example.com. , NS>_, the MaraDNS server returns the following response:
```
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "b.g.example.com. IN NS",
          ";ANSWER",
          "b.g.example.com. 60480 IN NS n.b.g.example.com.",
          ";AUTHORITY",
          ";ADDITIONAL",
          "n.b.g.example.com. 60480 IN A 1.1.1.1"
```
The **AA** bit is set in the response which should not be as this is a child NS record and the parent is not authoritative of the record. The server should return an empty answer but place `<b.g.example.com, NS>` in the authority section and the glue record in the additional section as per [RFC 6672, Section 3.2, Point 3B](https://tools.ietf.org/html/rfc6672#page-9).

A second minor issue occurs with queries  _<n.b.g.example.com. , NS>_,  _<something.n.b.g.example.com. , NS>_, and _<something.b.g.example.com. , NS>_. Maradns returns `<b.g.example.com, NS>`  in the answer section but does not set the AA bit correctly. The RFC and other implementations like BIND places the _NS_ record in the authority section instead of the answer section as it's not an authoritative record.

**Comment by samboy** [comment] 2020-11-07 19:10
Thank you for the detailed and informative report.

Any RFC after 2010 (RFC6672 is a 2012 RFC) is a wishlist item. 

I’m closing this bug, not because I will never fix this, but because this is a wishlist item, not a bug report.

I have stopped trying to keep playing the “RFCs breaking previously RFC compliant code” game.

**Closed by samboy** 2020-11-07 19:10 UTC

**Comment by samboy** [comment] 2020-11-08 05:27
I will, of course, be open to pull requests which implement this in the way which pedantically follows the post-2010 RFCs.

**Comment by samboy** [comment] 2020-11-08 17:28
In this case, MaraDNS’s rule is: If you specifically ask for a record which MaraDNS has, MaraDNS will return the record in the answer section. Even if it’s an NS record. It’s been a while since I looked at the code, but “fixing” this is, as I recall, something within the realm of reasonably possible.

Another thing: It’s actually OK and needs to be accounted for by recursive servers if an authoritative DNS server returns _only_ the answer in the answer section, and doesn’t have NS records in the authoritative section.

**Comment by samboy** [comment] 2020-11-08 18:11
Another thought: I am not unilaterally rejecting each and every post-2010 RFC. The sensible RFCs, the ones which make implementing DNS easier, are ones I do plan to implement.

For example, RFC8482 is simple, and what it does is patch DNS to remove one area where DNS was not really well thought out: ANY records (one can make a case for a special A-or-AAAA records query type, to deal with glueless NS referrals in a world where IPv6 is becoming mainstream, but even that requires cooperation from all of the DNS servers out there, which won’t happen). I’ll probably add it to MaraDNS next time I have a chance to work on MaraDNS.
