### ISSUE TITLE
TXT record bug?

### ISSUE THREAD

**Issue by chashock** [samboy/MaraDNS#81] opened 2020-08-31 23:10 UTC
Apologies if this isn't a bug, but I am trying to implement DKIM for an email server.  I have upgraded to MaraDNS 3.5.0015 from 2.0.14 where I first witnessed the behavior.  What I see is that TXT record behavior is not working as I believe it should be.  I've looked at every document I can find, and the csv2_txt man page would have me believe it should work fine, but the behavior I am seeing means my MTA is not getting the dkim1._domainkey record when querying the DNS server.

The behavior I see is that if I put ANYTHING besides just the domain name as part of a TXT record, it is not recognized / read / reported.  

If I put in my zone file

mydomain.net. +86400 txt 'testing' ~ 
or
% +86400 txt 'testing' ~

and use askmara Tmydomain.net. , I get the record showing properly in my list of txt records, which also includes a txt record for spf and a google authentication txt record with no hostnames (only domain).

If I put 

test.% +86400 txt 'testing' ~
or
test.mydomain.net. +86400 txt 'testing' ~ 

The record does NOT show up, though the spf and google records still do.

I originally thought I had a problem with the length of the key and broke it into multiple chunks, but that didn't make a difference, which I found by just shortening the text field itself.  If there is any hostname on the record it will not return a TXT record via askmara or an external query (opendkim-testkey, host, etc.).  I thought perhaps it was the underscore character, but that hasn't made any difference to remove it, and my MTA is specifically looking for that dkim1._domainkey.mydomain.net as the record name (and I don't think this can be changed).

I have turned verbosity up to 5 and no errors are reported outside of a couple of dangling CNAMEs that have never been a problem.

Apologies if this is an inappropriate post, I genuinely have tried over the course of several days tried to find an answer to this somewhere and have come up completely dry outside of a single entry in the old mailing lists indicating this should work, but I am formatted exactly like that message and it hasn't worked.  

Thanks for your consideration of this possible code issue.

**Comment by samboy** [comment] 2020-09-01 08:32
MaraDNS only allows DNS packets up to 512 bytes in size to be stored. Since DKIM records are larger than 512 bytes, MaraDNS truncates the record until it is 512 bytes or smaller.

I would suggest using ED25519 to make the DKIM record small enough to fit in a 512-byte DNS packet:

https://www.mailhardener.com/kb/how-to-use-dkim-with-ed25519

Not a bug, closing.

If you continue to get issues, please include a recipe to reproduce the bug.  Here is what I get:

```
# cat mararc
csv2_tilde_handling = 3
csv2 = {}
csv2["example.net."] = "db.example.net"
ipv4_bind_addresses = "127.0.0.1"
chroot_dir = "/etc/maradns"

# cat /etc/maradns/db.example.net
example.net.    txt '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' ~
#### example.net.    txt '234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901' ~
# maradns -f mararc
```

Then, in another window:

```
askmara Texample.net.
# Querying the server with the IP 127.0.0.1
# Question: Texample.net.
example.net. +86400 txt '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'
# NS replies:
example.net. +86400 ns synth-ip-7f000001.example.net.
# AR replies:
#synth-ip-7f000001.example.net. +86400 a 127.0.0.1
```

However, if I add a second long TXT record:

```
askmara Texample.net.
# Querying the server with the IP 127.0.0.1
# Remote server said: TRUNCATED
# NS replies:
# AR replies:
```

(There is a chance `nslookup` does not give a useful DNS error message here, so use `askmara` or `dig` instead).

**Closed by samboy** 2020-09-01 08:32 UTC

**Comment by samboy** [comment] 2020-09-01 08:36
Did you know that ED25519 is a cryptographic algorithm very specifically designed to allow public keys to fit in a DNS packet (yes, 512-byte DNS *was* the target for ED25519), and MaraDNS was one of the DNS servers ED25519 was specifically made for.

**Comment by chashock** [comment] 2020-09-01 09:52
Thank you, Sam, I will look at ED25519 as a way to fix this for my setup.  I do want to point out  you're not duplicating what I noted in the original comment.  You don't have a hostname, all you have is the domain name (example.net).  

As I said in the original, the length isn't the issue.  First, if I put the DKIM key into a TXT record without a hostname, just example.net, and issue askmara Texample.net, it responds with the full and proper value (as long as I use a 1024-bit key).  As soon as I change it to dkim1._domainkey.example.net, leaving everything else the same, it is as if that TXT record doesn't exist and it doesn't give an error on the restart of maraDNS.  If I put a 2048-bit key into the TXT record, it DOES respond with an error about the TXT record being too long upon the restart.  To use your recipe, put this in your db.example.net

testing.example.net.     txt   'testing'

and then askmaraT example.net.

For me, the record doesn't show up in the response.  It doesn't error, it just doesn't report the record.  I used askmara, never nslookup, too.

**Comment by samboy** [comment] 2020-09-01 17:45
Works for me:

```
# cat mararc
csv2_tilde_handling = 3
csv2 = {}
csv2["example.net."] = "db.example.net"
ipv4_bind_addresses = "127.0.0.1"
chroot_dir = "/etc/maradns"
```

```
# cat /etc/maradns/db.example.net
example.net.    txt 'This is some text' ~
hostname.example.net. txt 'Test' ~
testing.example.net. txt 'testing'
```

```
askmara Thostname.example.net.
# Querying the server with the IP 127.0.0.1
# Question: Thostname.example.net.
hostname.example.net. +86400 txt 'Test'
# NS replies:
#example.net. +86400 ns synth-ip-7f000001.example.net.
# AR replies:
#synth-ip-7f000001.example.net. +86400 a 127.0.0.1
```

```
askmara Ttesting.example.net.
# Querying the server with the IP 127.0.0.1
# Question: Ttesting.example.net.
testing.example.net. +86400 txt 'testing'
# NS replies:
#example.net. +86400 ns synth-ip-7f000001.example.net.
# AR replies:
#synth-ip-7f000001.example.net. +86400 a 127.0.0.1
```

```
askmara Texample.net.
# Querying the server with the IP 127.0.0.1
# Question: Texample.net.
example.net. +86400 txt 'This is some text'
# NS replies:
example.net. +86400 ns synth-ip-7f000001.example.net.
# AR replies:
#synth-ip-7f000001.example.net. +86400 a 127.0.0.1
```

This doesn’t recreate the issue either:

```
$ askmara Texample.net. ##########################
# Querying the server with the IP 127.0.0.1
# Remote server said: TRUNCATED
# NS replies:
# AR replies:
$ askmara Ttesting.example.net. ##########################
# Querying the server with the IP 127.0.0.1
# Question: Ttesting.example.net.
testing.example.net. +86400 txt 'testing'
# NS replies:
#example.net. +86400 ns synth-ip-7f000001.example.net.
# AR replies:
#synth-ip-7f000001.example.net. +86400 a 127.0.0.1
$ askmara Thostname.example.net.  #######################
# Querying the server with the IP 127.0.0.1
# Question: Thostname.example.net.
hostname.example.net. +86400 txt 'Test'
# NS replies:
#example.net. +86400 ns synth-ip-7f000001.example.net.
# AR replies:
#synth-ip-7f000001.example.net. +86400 a 127.0.0.1
$ cat mararc ###############################
csv2_tilde_handling = 3
csv2 = {}
csv2["example.net."] = "db.example.net"
ipv4_bind_addresses = "127.0.0.1"
chroot_dir = "/etc/maradns"
$ cat /etc/maradns/db.example.net ########################
example.net.    txt 'This is some text' ~
example.net.    txt '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' ~
example.net.    txt '234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901' ~
hostname.example.net. txt 'Test' ~
testing.example.net. txt 'testing'
```

Please provide the full contents of a zone file which reproproduces the bug. 

To do this, use \`\`\` in Markdown symtax to properly quote the zone file, for example:

\`\`\`
$ cat /etc/maradns/db.example.net
example.net.    txt 'This is some text' ~
hostname.example.net. txt 'Test' ~
testing.example.net. txt 'testing'
\`\`\`

Which will look like this:

```
$ cat /etc/maradns/db.example.net
example.net.    txt 'This is some text' ~
hostname.example.net. txt 'Test' ~
testing.example.net. txt 'testing'
```

**Comment by samboy** [comment] 2020-09-02 06:05
I will assume that the user figured out what the problem was and realized it was not a MaraDNS bug, but is too embarrassed to admit their mistake. I will lock this issue in 24 hours; GitHub bug reports are *not* a forum to get free MaraDNS support (keep in mind that 24-hour email support contracts for BIND cost $10,000 a year and go up very quickly from there).

**Comment by chashock** [comment] 2020-09-02 15:24
I will assume that you are just an ass, Mr Trenholme.  I explicitly stated that I wasn't sure this was a bug in filing my report, but your apparent inability to host and provide a community forum for your users to converse about issues they find left no real choice but to describe what I still believe is a bug and post it as such.  It still doesn't work for me, but this reaction and ridiculous posting just pushes me to move to another solution that actually does work properly with TXT records.  Thank you for helping me.

**Comment by samboy** [comment] 2020-09-02 19:21
Conversation locked because of now-deleted uncivil comment from “chashock”
