### ISSUE TITLE
upstream_servers does not support port other than 53

### ISSUE THREAD

**Issue by debiansid** [samboy/MaraDNS#7] opened 2015-01-31 02:46 UTC
Hi I need this little feature ,thanks.

**Comment by samboy** [comment] 2015-02-05 16:12
To quote the bottom of https://github.com/samboy/MaraDNS/blob/master/README.md

"It would require some large company or government agency paying me a full-time living wage to add significant new features to MaraDNS"

To quote the top of http://maradns.samiam.org (MaraDNS' web page, yeah it has one of those): "Now that I’m working as a professional software developer, the program is finished: I only provide bug fixes and other basic maintenance unless I’m getting paid."

Since this particular feature does not satisfy an "itch" I have right now, and since I'm not getting paid anything to write MaraDNS, I have no plans to implement that feature at this time. Since MaraDNS *is* open sourced, there is nothing stopping you from forking this repository and implementing that feature (please don't call your fork MaraDNS; call it something like "debianSidDNS")

Not a bug; closing.

**Closed by samboy** 2015-02-05 16:12 UTC
