### ISSUE TITLE
Set MAXIMUM TTL when using as recursive name server

### ISSUE THREAD

**Issue by rtguy** [samboy/MaraDNS#17] opened 2015-06-17 18:19 UTC
Hi - I'm looking to use MaraDNS solely as a recursive name server so that it will do DNS lookups for me.  For my particular need it is critical that the MaraDNS does not cache any records more than X seconds, regardless of the TTL. I will likely set X to be somewhere less than 5 minutes.

Is there a configuration option in MaraDNS to control this? If so, can you please explain how to do it as I don't see it in the docs or FAQ.  If there is not an option would you consider adding this - and in that case is there a way I can tell MaraDNS never to cache any results so each lookup is fresh (this may be a possible alternative assuming I can't set the max cache time very short).

Thank you!

**Comment by samboy** [comment] 2015-06-19 02:58
# Snarky answer

RTFM. STFU. HTH. HAND.

# In English

In order to more quickly get basic questions like this answered, please use the search functionality included on the MaraDNS web site:

http://maradns.samiam.org/search.html

If you search for "Maximum TTL" there, it will give you, in the first few results, this URL:

http://maradns.samiam.org/deadwood/doc/Deadwood.txt

This is the manual for Deadwood, MaraDNS' recursor; MaraDNS actually has extensive documentation. Searching that document for "ttl" will quickly find the parameter you are looking for.

# Use MaraDNS 2, not MaraDNS 1

Please be sure to use MaraDNS 2, not MaraDNS 1.  MaraDNS 1's support ends on Sunday, as I blogged about three years ago:

http://samiam.org/blog/20120621.html

# The GitHub support channel is mainly for reporting bugs

The GitHub support channel is for reporting bugs, not for support requests. Professional support contracts for DNS software _start at_ $10,000 a year and quickly get more more expensive than that.

# Not a bug, closing

It looks like I am going to have to hide the link to the GitHub tracking system behind a webpage which asks basic questions:

* Are you using MaraDNS 1 or MaraDNS 2? Sorry, MaraDNS 1 is no longer supported
* Did you search this webpage for an answer to your question? (include Google search box)
* Did you look through the manual for an answer to your question (include pointers to maradns, mararc, csv2, csv2_txt, duende, and Deadwood man pages)?
* Is this a bug report? Sorry, but I am not getting paid to do this and can not provide hand-holding support for free.

**Closed by samboy** 2015-06-19 02:58 UTC

**Comment by samboy** [comment] 2015-06-19 15:12
I have updated the support page to make sure they are using MaraDNS 2, they have read the manuals, they have search the web page, and they are filing a bug report (not asking for hand-holding support), before being given a link to this page.

http://maradns.samiam.org/support.html
