### ISSUE TITLE
timeout seconds not working in windows

### ISSUE THREAD

**Issue by lefebvresam** [samboy/MaraDNS#22] opened 2015-10-25 23:14 UTC
When i use timeout_seconds in config, the timeout always stays on 2 seconds when performing slow requests:

config file: (on 127.0.0.2 dns crypt proxy is running)

```
upstream_servers = {}
upstream_servers["."] = "127.0.0.2"
upstream_servers["lan."] = "192.168.2.2"
bind_address = "127.0.0.1"
recursive_acl = "127.0.0.1/24"
timeout_seconds = 6
random_seed_file = "sct.txt" 
cache_file = "dw_cache_bin"
filter_rfc1918 = 0
```

Restarting the service, and the timeout stays on 2 seconds:

Command window:

```
C:\Windows\System32>nslookup sam.saleconix.be
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
DNS request timed out.
    timeout was 2 seconds.
Name:    sam.ohbah.com
Address:  178.118.23.229
Aliases:  sam.saleconix.be
```
When running directly there is no timeout:

```
C:\Windows\System32>nslookup sam.saleconix.be 127.0.0.2
Server:  UnKnown
Address:  127.0.0.2

Non-authoritative answer:
Name:    sam.ohbah.com
Address:  178.118.23.229
Aliases:  sam.saleconix.be
```

**Comment by lefebvresam** [comment] 2015-10-26 16:58
During webbrowsing, most of the outgoing dns requests take more than 10 seconds to resolve which creates a very slow surfing experience.

**Comment by samboy** [comment] 2015-10-27 13:27
Works for me; I can and do get a 20 second timeout when set to do so. So:

* Are you using Deadwood 3.2.09?
* Did you increase maxprocs? Older versions of Deadwood have a somewhat low value of maxprocs that does not work with modern browers which perform DNS queries against every link on a given page.

A higher maxprocs is needed if having a high max_timeout, so that Deadwood can keep a large number of active outgoing queries going.

To increase maxprocs, add this line to your dwood3rc.txt file:

```
maxprocs = 32000
```

Also, if using Deadwood 3.2.08 or Deadwood 3.2.09, maxprocs’ default value (if not set in dwood3rc.txt) has increased from 32 to 1024.

Not a bug, closing.

**Closed by samboy** 2015-10-27 13:27 UTC

**Comment by lefebvresam** [comment] 2015-11-03 11:12
I use Deadwood 3.2.09 win 32.
I used now in my config:

```
...
timeout_seconds = 20
maxprocs = 32000
...
```

How can you explain why I have this strange behavior. Resolving over Deadwood and DnsCrypt takes several attemps with 2 second timeouts. Resolving directly to 8.8.8.8 gives an immediate answer.

```
C:\Windows\System32>nslookup sam.saleconix.be
Server:  localhost
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
Non-authoritative answer:
DNS request timed out.
    timeout was 2 seconds.
Name:    sam.ohbah.com
Address:  178.118.23.229
Aliases:  sam.saleconix.be


C:\Windows\System32>nslookup sam.saleconix.be 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    sam.ohbah.com
Address:  178.118.23.229
Aliases:  sam.saleconix.be
```

**Comment by samboy** [comment] 2015-11-07 07:14
You know, this is not a bug report. But, since you asked:

* Don’t use nslookup.  Use dig.  The two-second timeout is coming from nslookup, not from Deadwood. 
* It looks like the issue is some incompatibility between dnscrypt and Deadwood. 

Here is my official response: **Using a dnscrypt proxy is not a supported configuration for Deadwood, and debugging dnscrypt-specific issues goes beyond the boundaries of support I offer for Deadwood.** 

You’re not paying me enough for me to provide you hand-holding support.

For those who need professional DNS support, please consider a commercial support contract for BIND; note that they cost around $10,000 a year or more. 

And, oh a simple [Google Search](http://lmgtfy.com/?q=maradns+deadwood+dnscrypt) gives me this link:

http://www.wilderssecurity.com/threads/using-cloudns-for-dns-resolution-integrity-authenticity-confidentiality.351695/

Locking comments.
