### ISSUE TITLE
Could not open hash at dw_cache_bin for reading

### ISSUE THREAD

**Issue by kaykamel** [samboy/MaraDNS#79] opened 2020-07-21 07:47 UTC
I am getting this error when resolving .

[dwood3rc.txt](https://github.com/samboy/MaraDNS/files/4952016/dwood3rc.txt)

**Comment by samboy** [comment] 2020-07-22 15:15
This is a non-fatal error which can be safely ignored. The cache file just keeps copies of previously resolved DNS names around between invocations of Deadwood; if the cache file can’t be read, then DNS resolution might be a bit slower for some names after starting up Deadwood, but everything will be OK.

Not a bug, closing.

**Closed by samboy** 2020-07-22 15:15 UTC

**Comment by samboy** [comment] 2020-07-25 10:43
MaraDNS 3.5.0008 makes this error message only visible if using a non-default value for `verbose_level` (10 or more). This message will no longer be visible for most users.
